#!/usr/bin/env bash
tmpbg='/tmp/screen.png'

if [ -z "$WAYLAND_DISPLAY" ]; then
  echo "running in X11"
  scrot "$tmpbg";
else
  echo "running in wayland"
  swaygrab "$tmpbg";
fi

convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"

convert "$tmpbg" -gravity center -composite -matte "$tmpbg"

if [ -z "$WAYLAND_DISPLAY" ]; then
  i3lock -i "$tmpbg";
else
  swaylock -i "$tmpbg";
fi
