require('custom-conf')
require('plugins')
require('statusline')
require('lsp')
require('cmp-setup')
require('vim-test')
require('telescope-conf')
require('other')
vim.cmd('source ~/.config/nvim/custom.vim')
